# 基础镜像
FROM redis
# author
MAINTAINER lynn

# 挂载目录
VOLUME /home/lynn/redis
# 创建目录
RUN mkdir -p /home/lynn/redis
# 指定路径
WORKDIR /home/lynn/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/lynn/redis/redis.conf
