apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: skywalking-ui
  name: skywalking-ui
  namespace: kube-ruoyi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking-ui
  template:
    metadata:
      labels:
        app: skywalking-ui
    spec:
      containers:
      - name: skywalking-ui
        image:  apache/skywalking-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: console
        env:
        - name: SW_OAP_ADDRESS
          value: http://skywalking:12800
        - name: TZ
          value: Asia/Shanghai
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-ui
  namespace: kube-ruoyi
spec:
  ports:
    - port: 8080
      nodePort: 30088
  selector:
    app: skywalking-ui # 该 Service 会将所有具有标签 app: mysql-labels-app暴露到一个抽象的 Service 端口上（targetPort：容器接收流量的端口；port：可任意取值的抽象的 Service 端口，其他 Pod 通过该端口访问 Service
  type: NodePort