# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER lynn

ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone

# 挂载目录
VOLUME /home/lynn
# 创建目录
RUN mkdir -p /home/lynn
# 指定路径
WORKDIR /home/lynn
# 复制jar文件到路径
COPY ./jar/*.* /home/lynn/
RUN  chmod +x /home/lynn/startup.sh
# 启动网关服务
ENTRYPOINT ["/home/lynn/startup.sh"]