apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
spec:
  type: NodePort
  publishNotReadyAddresses: true
  ports:
    - port: 9000
      name: tcp
      targetPort: 9000
    - port: 9090
      name: console
      targetPort: 9090
      nodePort: 30090
  selector:
    app: minio