# 基础镜像
FROM  eclipse-temurin:21.0.2_13-jre
# author
LABEL author="ryas"

# 定义一个环境变量JVM_OPTS，用户可以通过它传递JVM参数
ENV JVM_OPTS=""

# 挂载容器内目录
VOLUME /home/ryas
# 容器内创建目录
RUN mkdir -p /home/ryas
# 指定容器内工作路径
WORKDIR /home/ryas
# 复制jar文件到路径
COPY ./jar/ruoyi-auth.jar /home/ryas/ruoyi-auth.jar
# 启动服务
ENTRYPOINT exec java $JVM_OPTS -jar ruoyi-auth.jar
