# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER ruoyi

# 挂载目录
VOLUME /home/ruoyi
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi
# 复制jar文件到路径
COPY ./jar/*.* /home/ruoyi/
RUN  chmod +x /home/ruoyi/startup.sh
# 启动网关服务
# ENTRYPOINT ["java","-jar","ruoyi-gateway.jar","ruoyi-auth.jar"]
ENTRYPOINT ["/home/ruoyi/startup.sh"]