{
  "id" : "a5f46d89e2454149b649d2dd542e522d",
  "script" : null,
  "groupId" : "2b0ce800b6c543efa284ae695e14e4eb",
  "name" : "文件下载",
  "createTime" : 1615983934415,
  "updateTime" : 1615983934415,
  "method" : "GET",
  "path" : "/download",
  "parameters" : [ ],
  "option" : "[]",
  "requestBody" : "",
  "headers" : [ ],
  "responseBody" : null,
  "description" : null,
  "optionMap" : { }
}
================================
import response;
return response.download('中文测试','str.txt');