# 基础镜像
FROM nginx
# author
MAINTAINER lynn

# 挂载目录
VOLUME /home/lynn/projects/lynn-ui
# 创建目录
RUN mkdir -p /home/lynn/projects/lynn-ui
# 指定路径
WORKDIR /home/lynn/projects/lynn-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/lynn/projects/lynn-ui
