package com.ruoyi.wms.domain;

import com.ruoyi.common.core.annotation.Excel;
import com.ruoyi.common.core.web.domain.ExtBaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * This class was generated by MyBatis Generator.
 *
 * <ul>
 *   <li> Table: WMS_B_BASE_STOCK </li>
 *   <li> Remarks: 基本库存表 </li>
 * </ul>
 *
 * @author ryas
 * created on 2024-02-22
 */
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
@Data
public class BaseStock extends ExtBaseEntity implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    //==================== ↓↓↓↓↓↓ 非表字段 ↓↓↓↓↓↓ ====================

    /**
     * 仓库名称
     */
    private String whsName;

    /**
     * 物品名称
     */
    private String itemName;

    /**
     * 标准单位代码
     */
    private String stdUnitCd;

    /**
     * 标准单位名称
     */
    private String stdUnitName;

    /**
     * 包装单位代码
     */
    private String pkgUnitCd;

    /**
     * 包装单位名称
     */
    private String pkgUnitName;

    //==================== ↓↓↓↓↓↓ 扩展方法 ↓↓↓↓↓↓ ====================

    //==================== ↓↓↓↓↓↓ 表字段 ↓↓↓↓↓↓ ====================

    /**
     * 仓库代码
     */
    @Excel(name = "仓库代码", sort = 1)
    private String whsCd;

    /**
     * 货架号
     */
    @Excel(name = "货架号", sort = 2)
    private String stgBinCd;

    /**
     * 物品代码
     */
    @Excel(name = "物品代码", sort = 3)
    private String itemCd;

    /**
     * 批号
     */
    @Excel(name = "批号", sort = 4)
    private String lotNo;

    /**
     * 子批号
     */
    @Excel(name = "子批号", sort = 5)
    private String subLotNo;

    /**
     * 从属部门ID
     */
    private Integer deptId;

    /**
     * 标准单位数量
     */
    @Excel(name = "标准单位数量", sort = 6)
    private BigDecimal stdUnitQty;

    /**
     * 包装单位数量
     */
    @Excel(name = "包装单位数量", sort = 7)
    private BigDecimal pkgUnitQty;

    /**
     * 序列号
     */
    @Excel(name = "序列号", sort = 8)
    private String serialNo;

    /**
     * 托盘ID
     */
    @Excel(name = "托盘ID", sort = 9)
    private String palletId;

    /**
     * 父托盘ID
     */
    @Excel(name = "父托盘ID", sort = 10)
    private String parentPalletId;

    /**
     * 备注1
     */
    private String remark1;

    /**
     * 备注2
     */
    private String remark2;

    /**
     * 备注3
     */
    private String remark3;

    /**
     * 备注4
     */
    private String remark4;

    /**
     * 备注5
     */
    private String remark5;

}