package com.ruoyi.wms.domain;

import com.ruoyi.common.core.annotation.Excel;
import com.ruoyi.common.core.web.domain.ExtBaseEntity;

import java.io.Serial;
import java.io.Serializable;

/**
 * This class was generated by MyBatis Generator.
 *
 * <ul>
 *   <li> Table: WMS_M_GOODS_TYPE_INFO </li>
 *   <li> Remarks: 物品类型表 </li>
 * </ul>
 *
 * @author ryas
 * created on 2024-02-18
 */
public class GoodsType extends ExtBaseEntity implements Serializable {
    /**
     *   物品类型编码
     */
    @Excel(name = "物品类型编码")
    private String goodsTypeCd;

    /**
     *   从属部门ID
     */
    private Integer deptId;

    /**
     *   物品类型名称
     */
    @Excel(name = "物品类型名称")
    private String goodsTypeName;

    /**
     *   备注1
     */
    @Excel(name = "备注")
    private String remark1;

    /**
     *   备注2
     */
    private String remark2;

    /**
     *   备注3
     */
    private String remark3;

    /**
     *   备注4
     */
    private String remark4;

    /**
     *   备注5
     */
    private String remark5;

    @Serial
    private static final long serialVersionUID = 1L;

    public String getGoodsTypeCd() {
        return goodsTypeCd;
    }

    public void setGoodsTypeCd(String goodsTypeCd) {
        this.goodsTypeCd = goodsTypeCd == null ? null : goodsTypeCd.trim();
    }

    public Integer getDeptId() {
        return deptId;
    }

    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    public String getGoodsTypeName() {
        return goodsTypeName;
    }

    public void setGoodsTypeName(String goodsTypeName) {
        this.goodsTypeName = goodsTypeName == null ? null : goodsTypeName.trim();
    }

    public String getRemark1() {
        return remark1;
    }

    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    public String getRemark2() {
        return remark2;
    }

    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    public String getRemark3() {
        return remark3;
    }

    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    public String getRemark4() {
        return remark4;
    }

    public void setRemark4(String remark4) {
        this.remark4 = remark4 == null ? null : remark4.trim();
    }

    public String getRemark5() {
        return remark5;
    }

    public void setRemark5(String remark5) {
        this.remark5 = remark5 == null ? null : remark5.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", goodsTypeCd=").append(goodsTypeCd);
        sb.append(", deptId=").append(deptId);
        sb.append(", goodsTypeName=").append(goodsTypeName);
        sb.append(", remark1=").append(remark1);
        sb.append(", remark2=").append(remark2);
        sb.append(", remark3=").append(remark3);
        sb.append(", remark4=").append(remark4);
        sb.append(", remark5=").append(remark5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}