package com.ruoyi.wms.domain;

import com.ruoyi.common.core.web.domain.ExtBaseEntity;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * This class was generated by MyBatis Generator.
 *
 * <ul>
 *   <li> Table: WMS_B_INV_TRANS_HIS </li>
 *   <li> Remarks: 入出库履历表 </li>
 * </ul>
 *
 * @author ryas
 * created on 2024-02-22
 */
public class InvTransHis extends ExtBaseEntity implements Serializable {
    /**
     *   入出库履历号
     */
    private String invTransNo;

    /**
     *   从属部门ID
     */
    private Integer deptId;

    /**
     *   入出库类型(1:入库,2:出库)
     */
    private Integer invTransType;

    /**
     *   仓库代码
     */
    private String whsCd;

    /**
     *   货架号
     */
    private String stgBinCd;

    /**
     *   托盘ID
     */
    private String palletId;

    /**
     *   标准单位数量
     */
    private BigDecimal stdUnitQty;

    /**
     *   包装单位数量
     */
    private BigDecimal pkgUnitQty;

    /**
     *   交易单号
     */
    private String transOrderNo;

    /**
     *   交易单明细号
     */
    private String transOrderDetlNo;

    /**
     *   操作员
     */
    private String operator;

    /**
     *   业务区分
     */
    private String businessCls;

    /**
     *   物品代码
     */
    private String itemCd;

    /**
     *   批号
     */
    private String lotNo;

    /**
     *   子批号
     */
    private String subLotNo;

    /**
     *   序列号
     */
    private String serialNo;

    /**
     *   入出库理由
     */
    private String reason;

    /**
     *   备注1
     */
    private String remark1;

    /**
     *   备注2
     */
    private String remark2;

    /**
     *   备注3
     */
    private String remark3;

    /**
     *   备注4
     */
    private String remark4;

    /**
     *   备注5
     */
    private String remark5;

    @Serial
    private static final long serialVersionUID = 1L;

    public String getInvTransNo() {
        return invTransNo;
    }

    public void setInvTransNo(String invTransNo) {
        this.invTransNo = invTransNo == null ? null : invTransNo.trim();
    }

    public Integer getDeptId() {
        return deptId;
    }

    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    public Integer getInvTransType() {
        return invTransType;
    }

    public void setInvTransType(Integer invTransType) {
        this.invTransType = invTransType;
    }

    public String getWhsCd() {
        return whsCd;
    }

    public void setWhsCd(String whsCd) {
        this.whsCd = whsCd == null ? null : whsCd.trim();
    }

    public String getStgBinCd() {
        return stgBinCd;
    }

    public void setStgBinCd(String stgBinCd) {
        this.stgBinCd = stgBinCd == null ? null : stgBinCd.trim();
    }

    public String getPalletId() {
        return palletId;
    }

    public void setPalletId(String palletId) {
        this.palletId = palletId == null ? null : palletId.trim();
    }

    public BigDecimal getStdUnitQty() {
        return stdUnitQty;
    }

    public void setStdUnitQty(BigDecimal stdUnitQty) {
        this.stdUnitQty = stdUnitQty;
    }

    public BigDecimal getPkgUnitQty() {
        return pkgUnitQty;
    }

    public void setPkgUnitQty(BigDecimal pkgUnitQty) {
        this.pkgUnitQty = pkgUnitQty;
    }

    public String getTransOrderNo() {
        return transOrderNo;
    }

    public void setTransOrderNo(String transOrderNo) {
        this.transOrderNo = transOrderNo == null ? null : transOrderNo.trim();
    }

    public String getTransOrderDetlNo() {
        return transOrderDetlNo;
    }

    public void setTransOrderDetlNo(String transOrderDetlNo) {
        this.transOrderDetlNo = transOrderDetlNo == null ? null : transOrderDetlNo.trim();
    }

    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    public String getBusinessCls() {
        return businessCls;
    }

    public void setBusinessCls(String businessCls) {
        this.businessCls = businessCls == null ? null : businessCls.trim();
    }

    public String getItemCd() {
        return itemCd;
    }

    public void setItemCd(String itemCd) {
        this.itemCd = itemCd == null ? null : itemCd.trim();
    }

    public String getLotNo() {
        return lotNo;
    }

    public void setLotNo(String lotNo) {
        this.lotNo = lotNo == null ? null : lotNo.trim();
    }

    public String getSubLotNo() {
        return subLotNo;
    }

    public void setSubLotNo(String subLotNo) {
        this.subLotNo = subLotNo == null ? null : subLotNo.trim();
    }

    public String getSerialNo() {
        return serialNo;
    }

    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    public String getRemark1() {
        return remark1;
    }

    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    public String getRemark2() {
        return remark2;
    }

    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    public String getRemark3() {
        return remark3;
    }

    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    public String getRemark4() {
        return remark4;
    }

    public void setRemark4(String remark4) {
        this.remark4 = remark4 == null ? null : remark4.trim();
    }

    public String getRemark5() {
        return remark5;
    }

    public void setRemark5(String remark5) {
        this.remark5 = remark5 == null ? null : remark5.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", invTransNo=").append(invTransNo);
        sb.append(", deptId=").append(deptId);
        sb.append(", invTransType=").append(invTransType);
        sb.append(", whsCd=").append(whsCd);
        sb.append(", stgBinCd=").append(stgBinCd);
        sb.append(", palletId=").append(palletId);
        sb.append(", stdUnitQty=").append(stdUnitQty);
        sb.append(", pkgUnitQty=").append(pkgUnitQty);
        sb.append(", transOrderNo=").append(transOrderNo);
        sb.append(", transOrderDetlNo=").append(transOrderDetlNo);
        sb.append(", operator=").append(operator);
        sb.append(", businessCls=").append(businessCls);
        sb.append(", itemCd=").append(itemCd);
        sb.append(", lotNo=").append(lotNo);
        sb.append(", subLotNo=").append(subLotNo);
        sb.append(", serialNo=").append(serialNo);
        sb.append(", reason=").append(reason);
        sb.append(", remark1=").append(remark1);
        sb.append(", remark2=").append(remark2);
        sb.append(", remark3=").append(remark3);
        sb.append(", remark4=").append(remark4);
        sb.append(", remark5=").append(remark5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}