package com.ruoyi.wms.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.ruoyi.common.core.web.domain.ExtBaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import org.springframework.web.multipart.MultipartFile;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * This class was generated by MyBatis Generator.
 *
 * <ul>
 *   <li> Table: WMS_M_ITEM_INFO </li>
 *   <li> Remarks: 物品基础信息表 </li>
 * </ul>
 *
 * @author ryas
 * created on 2024-02-20
 */
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
@Data
public class ItemInfo extends ExtBaseEntity implements Serializable {
    @Serial
    private static final long serialVersionUID = 1L;

    //==================== ↓↓↓↓↓↓ 非表字段 ↓↓↓↓↓↓ ====================

    /**
     * (非表字段)
     * 物品类型名称
     */
    private String itemTypeName;

    /**
     * (非表字段)
     * 标准单位名称
     */
    private String stdUnitName;

    /**
     * (非表字段)
     * 包装单位名称
     */
    private String pkgUnitName;

    /**
     * (非表字段)
     * 图片文件
     */
    private MultipartFile[] itemImages;

    //==================== ↓↓↓↓↓↓ 扩展方法 ↓↓↓↓↓↓ ====================

    @JsonIgnore
    public boolean isEnabled() {
        return enableFlg != null && enableFlg == 1;
    }

    @JsonIgnore
    public boolean isLotNoManaged() {
        return lotNoMgmtCls != null && lotNoMgmtCls == 1;
    }

    @JsonIgnore
    public MultipartFile getItemImageFirst() {
        return itemImages != null && itemImages.length > 0 ? itemImages[0] : null;
    }

    //==================== ↓↓↓↓↓↓ 表字段 ↓↓↓↓↓↓ ====================

    /**
     * 物品代码
     */
    private String itemCd;

    /**
     * 从属部门ID
     */
    private Integer deptId;

    /**
     * 物品名称
     */
    private String itemName;

    /**
     * 供应商
     */
    private String supplier;

    /**
     * 筹备提前期
     */
    private BigDecimal prepLeadTime;

    /**
     * 入库提前期
     */
    private BigDecimal instockLeadTime;

    /**
     * 放置期
     */
    private BigDecimal restingPeriod;

    /**
     * 出库提前期
     */
    private BigDecimal outstockLeadTime;

    /**
     * 规格1
     */
    private String spec1;

    /**
     * 规格2
     */
    private String spec2;

    /**
     * 规格3
     */
    private String spec3;

    /**
     * 规格4
     */
    private String spec4;

    /**
     * 规格5
     */
    private String spec5;

    /**
     * 分类1
     */
    private String cls1;

    /**
     * 分类2
     */
    private String cls2;

    /**
     * 分类3
     */
    private String cls3;

    /**
     * 分类4
     */
    private String cls4;

    /**
     * 分类5
     */
    private String cls5;

    /**
     * 备注1
     */
    private String remark1;

    /**
     * 备注2
     */
    private String remark2;

    /**
     * 备注3
     */
    private String remark3;

    /**
     * 备注4
     */
    private String remark4;

    /**
     * 备注5
     */
    private String remark5;

    /**
     * 供货周期
     */
    private String deliveryPeriod;

    /**
     * 默认库位号
     */
    private String defaultStgBinCd;

    /**
     * 启用标志
     */
    private Integer enableFlg;

    /**
     * 安全库存量
     */
    private BigDecimal safetyStock;

    /**
     * 最大库存量
     */
    private BigDecimal maxInvQty;

    /**
     * 发起购买的阈值
     */
    private BigDecimal purchLimitQty;

    /**
     * 物品区分
     */
    private String goodsCls;

    /**
     * 批号管理区分(0:不管理, 1:管理)
     */
    private Integer lotNoMgmtCls;

    /**
     * 物品类型代码
     */
    private String itemTypeCd;

    /**
     * 标准单位代码
     */
    private String stdUnitCd;

    /**
     * 包装单位代码
     */
    private String pkgUnitCd;

    /**
     * 出库申请最小数量
     */
    private BigDecimal outstockReqMinQty;

    /**
     * 出库单位区分
     */
    private String outstockUnitCls;

    /**
     * 单位净重
     */
    private BigDecimal netWeightPerUnit;

    /**
     * 自身体积(M3)
     */
    private BigDecimal ownVolM3;

    /**
     * 尺寸(长)
     */
    private BigDecimal sizeD;

    /**
     * 尺寸(宽)
     */
    private BigDecimal sizeW;

    /**
     * 尺寸(高)
     */
    private BigDecimal sizeH;

    /**
     * 包装要求描述
     */
    private String pkgRqmtDesc;

    /**
     * 码放要求描述
     */
    private String stackingRqmtDesc;

    /**
     * 储存要求描述
     */
    private String stgRqmtDesc;

    /**
     * 生产商
     */
    private String manufacturer;

    /**
     * 图片ID
     */
    private String pictureId;

    /**
     * 图片URL
     */
    private String pictureUrl;

}