package com.ruoyi.wms.domain;

import com.ruoyi.common.core.annotation.Excel;
import com.ruoyi.common.core.web.domain.ExtBaseEntity;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * This class was generated by MyBatis Generator.
 *
 * <ul>
 *   <li> Table: WMS_M_WAREHOUSE_INFO </li>
 *   <li> Remarks: 仓库基础信息表 </li>
 * </ul>
 *
 * @author ryas
 * created on 2024-02-18
 */
public class WarehouseInfo extends ExtBaseEntity implements Serializable {
    /**
     * 仓库代码
     */
    @Excel(name = "仓库代码")
    private String whsCd;

    /**
     * 从属部门ID
     */
    private Integer deptId;

    /**
     * 仓库名称
     */
    @Excel(name = "仓库名称")
    private String whsName;

    /**
     * 仓库类型代码
     */
    private String whsTypeCd;

    /**
     * 缩写
     */
    @Excel(name = "缩写")
    private String abbr;

    /**
     * 地址1
     */
    @Excel(name = "地址1")
    private String addr1;

    /**
     * 地址2
     */
    @Excel(name = "地址2")
    private String addr2;

    /**
     * 地址3
     */
    @Excel(name = "地址3")
    private String addr3;

    /**
     * 联系电话
     */
    @Excel(name = "联系电话")
    private String phoneNo;

    /**
     * 邮编
     */
    @Excel(name = "邮编")
    private String zipCd;

    /**
     * 联系邮箱
     */
    @Excel(name = "联系邮箱")
    private String email;

    /**
     * 传真号
     */
    @Excel(name = "传真号")
    private String faxNo;

    /**
     * 负责人
     */
    @Excel(name = "负责人")
    private String respPerson;

    /**
     * 区域
     */
    @Excel(name = "区域")
    private String area;

    /**
     * 租赁费用
     */
    @Excel(name = "租赁费用")
    private BigDecimal rentalFee;

    /**
     * 存储费用
     */
    @Excel(name = "存储费用")
    private BigDecimal storingFee;

    private String remark1;

    private String remark2;

    private String remark3;

    private String remark4;

    private String remark5;

    @Serial
    private static final long serialVersionUID = 1L;

    public String getWhsCd() {
        return whsCd;
    }

    public void setWhsCd(String whsCd) {
        this.whsCd = whsCd == null ? null : whsCd.trim();
    }

    public Integer getDeptId() {
        return deptId;
    }

    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    public String getWhsName() {
        return whsName;
    }

    public void setWhsName(String whsName) {
        this.whsName = whsName == null ? null : whsName.trim();
    }

    public String getWhsTypeCd() {
        return whsTypeCd;
    }

    public void setWhsTypeCd(String whsTypeCd) {
        this.whsTypeCd = whsTypeCd == null ? null : whsTypeCd.trim();
    }

    public String getAbbr() {
        return abbr;
    }

    public void setAbbr(String abbr) {
        this.abbr = abbr == null ? null : abbr.trim();
    }

    public String getAddr1() {
        return addr1;
    }

    public void setAddr1(String addr1) {
        this.addr1 = addr1 == null ? null : addr1.trim();
    }

    public String getAddr2() {
        return addr2;
    }

    public void setAddr2(String addr2) {
        this.addr2 = addr2 == null ? null : addr2.trim();
    }

    public String getAddr3() {
        return addr3;
    }

    public void setAddr3(String addr3) {
        this.addr3 = addr3 == null ? null : addr3.trim();
    }

    public String getPhoneNo() {
        return phoneNo;
    }

    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    public String getZipCd() {
        return zipCd;
    }

    public void setZipCd(String zipCd) {
        this.zipCd = zipCd == null ? null : zipCd.trim();
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public String getFaxNo() {
        return faxNo;
    }

    public void setFaxNo(String faxNo) {
        this.faxNo = faxNo == null ? null : faxNo.trim();
    }

    public String getRespPerson() {
        return respPerson;
    }

    public void setRespPerson(String respPerson) {
        this.respPerson = respPerson == null ? null : respPerson.trim();
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    public BigDecimal getRentalFee() {
        return rentalFee;
    }

    public void setRentalFee(BigDecimal rentalFee) {
        this.rentalFee = rentalFee;
    }

    public BigDecimal getStoringFee() {
        return storingFee;
    }

    public void setStoringFee(BigDecimal storingFee) {
        this.storingFee = storingFee;
    }

    public String getRemark1() {
        return remark1;
    }

    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    public String getRemark2() {
        return remark2;
    }

    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    public String getRemark3() {
        return remark3;
    }

    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    public String getRemark4() {
        return remark4;
    }

    public void setRemark4(String remark4) {
        this.remark4 = remark4 == null ? null : remark4.trim();
    }

    public String getRemark5() {
        return remark5;
    }

    public void setRemark5(String remark5) {
        this.remark5 = remark5 == null ? null : remark5.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", whsCd=").append(whsCd);
        sb.append(", deptId=").append(deptId);
        sb.append(", whsName=").append(whsName);
        sb.append(", whsTypeCd=").append(whsTypeCd);
        sb.append(", abbr=").append(abbr);
        sb.append(", addr1=").append(addr1);
        sb.append(", addr2=").append(addr2);
        sb.append(", addr3=").append(addr3);
        sb.append(", phoneNo=").append(phoneNo);
        sb.append(", zipCd=").append(zipCd);
        sb.append(", email=").append(email);
        sb.append(", faxNo=").append(faxNo);
        sb.append(", respPerson=").append(respPerson);
        sb.append(", area=").append(area);
        sb.append(", rentalFee=").append(rentalFee);
        sb.append(", storingFee=").append(storingFee);
        sb.append(", remark1=").append(remark1);
        sb.append(", remark2=").append(remark2);
        sb.append(", remark3=").append(remark3);
        sb.append(", remark4=").append(remark4);
        sb.append(", remark5=").append(remark5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}