package com.ruoyi.common.services.domain;

import com.ruoyi.common.core.web.domain.BaseEntity;

import java.io.Serial;
import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 *
 * <ul>
 *   <li> Table: sys_job_data_log </li>
 *   <li> Remarks: 定时任务数据日志表 </li>
 * </ul>
 *
 * @author ryas
 * created on 2024-02-20
 */
public class JobDataLog extends BaseEntity implements Serializable {
    /**
     *   任务数据日志ID
     */
    private Long logId;

    /**
     *   执行开始时间
     */
    private Date startTime;

    /**
     *   执行结束时间
     */
    private Date endTime;

    /**
     *   日志内容
     */
    private String message;

    /**
     *   日志类型
     */
    private String logType;

    /**
     *   状态（0正常执行 1异常）
     */
    private String status;

    /**
     *   任务执行类
     */
    private String jobClass;

    /**
     *   任务执行方法名
     */
    private String jobMethod;

    @Serial
    private static final long serialVersionUID = 1L;

    public static JobDataLog of(Date startTime, Date endTime, String message, String logType, String status, String jobClass, String jobMethod) {
        JobDataLog jobDataLog = new JobDataLog();
        jobDataLog.setStartTime(startTime);
        jobDataLog.setEndTime(endTime);
        jobDataLog.setMessage(message);
        jobDataLog.setLogType(logType);
        jobDataLog.setStatus(status);
        jobDataLog.setJobClass(jobClass);
        jobDataLog.setJobMethod(jobMethod);
        return jobDataLog;
    }

    public static JobDataLog of(Date startTime, Date endTime, String message, String logType, String status) {
        return of(startTime, endTime, message, logType, status, null, null);
    }

    public static JobDataLog of(String message, String logType, String status) {
        return of(null, null, message, logType, status);
    }

    public Long getLogId() {
        return logId;
    }

    public void setLogId(Long logId) {
        this.logId = logId;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    public String getLogType() {
        return logType;
    }

    public void setLogType(String logType) {
        this.logType = logType == null ? null : logType.trim();
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    public String getJobClass() {
        return jobClass;
    }

    public void setJobClass(String jobClass) {
        this.jobClass = jobClass == null ? null : jobClass.trim();
    }

    public String getJobMethod() {
        return jobMethod;
    }

    public void setJobMethod(String jobMethod) {
        this.jobMethod = jobMethod == null ? null : jobMethod.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logId=").append(logId);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", message=").append(message);
        sb.append(", logType=").append(logType);
        sb.append(", status=").append(status);
        sb.append(", jobClass=").append(jobClass);
        sb.append(", jobMethod=").append(jobMethod);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}