package com.ruoyi.common.services.domain;

import com.ruoyi.common.core.web.domain.BaseEntity;

import java.io.Serial;
import java.io.Serializable;

/**
 * This class was generated by MyBatis Generator.
 *
 * <ul>
 *   <li> Table: sys_file </li>
 *   <li> Remarks: 文件存储记录表 </li>
 * </ul>
 *
 * @author ryas
 * created on 2024-02-19
 */
public class SysFile extends BaseEntity implements Serializable {
    /**
     *   文件ID
     */
    private String fileId;

    /**
     *   保存的文件名称
     */
    private String savedName;

    /**
     *   原始文件名称
     */
    private String originalName;

    /**
     *   文件路径
     */
    private String filePath;

    /**
     *   文件后缀
     */
    private String extension;

    /**
     *   存储方式
     */
    private String storageType;

    /**
     *   获取文件的URL
     */
    private String requestUrl;

    /**
     *   文件大小(Byte)
     */
    private Long fileSize;

    @Serial
    private static final long serialVersionUID = 1L;

    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    public String getSavedName() {
        return savedName;
    }

    public void setSavedName(String savedName) {
        this.savedName = savedName == null ? null : savedName.trim();
    }

    public String getOriginalName() {
        return originalName;
    }

    public void setOriginalName(String originalName) {
        this.originalName = originalName == null ? null : originalName.trim();
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    public String getExtension() {
        return extension;
    }

    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    public String getStorageType() {
        return storageType;
    }

    public void setStorageType(String storageType) {
        this.storageType = storageType == null ? null : storageType.trim();
    }

    public String getRequestUrl() {
        return requestUrl;
    }

    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl == null ? null : requestUrl.trim();
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fileId=").append(fileId);
        sb.append(", savedName=").append(savedName);
        sb.append(", originalName=").append(originalName);
        sb.append(", filePath=").append(filePath);
        sb.append(", extension=").append(extension);
        sb.append(", storageType=").append(storageType);
        sb.append(", requestUrl=").append(requestUrl);
        sb.append(", fileSize=").append(fileSize);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}