package com.ruoyi.common.services.domain;

import com.ruoyi.common.core.web.domain.BaseEntity;

import java.io.Serial;
import java.io.Serializable;

/**
 * This class was generated by MyBatis Generator.
 *
 * <ul>
 *   <li> Table: sys_seq_result </li>
 *   <li> Remarks: 序列号生成记录表 </li>
 * </ul>
 *
 * @author ryas
 * created on 2024-02-19
 */
public class SysSeqResult extends BaseEntity implements Serializable {
    /**
     *   序列号ID
     */
    private Long seqId;

    /**
     *   序列号识别码
     */
    private String seqDistCd;

    /**
     *   前缀
     */
    private String prefix;

    /**
     *   分隔符1
     */
    private String separator1;

    /**
     *   日期值
     */
    private String dateVal;

    /**
     *   分隔符2
     */
    private String separator2;

    /**
     *   当前序列号
     */
    private Integer seqNo;

    /**
     *   备注1
     */
    private String remark1;

    /**
     *   备注2
     */
    private String remark2;

    /**
     *   备注3
     */
    private String remark3;

    /**
     *   备注4
     */
    private String remark4;

    /**
     *   备注5
     */
    private String remark5;

    @Serial
    private static final long serialVersionUID = 1L;

    public Long getSeqId() {
        return seqId;
    }

    public void setSeqId(Long seqId) {
        this.seqId = seqId;
    }

    public String getSeqDistCd() {
        return seqDistCd;
    }

    public void setSeqDistCd(String seqDistCd) {
        this.seqDistCd = seqDistCd == null ? null : seqDistCd.trim();
    }

    public String getPrefix() {
        return prefix;
    }

    public void setPrefix(String prefix) {
        this.prefix = prefix == null ? null : prefix.trim();
    }

    public String getSeparator1() {
        return separator1;
    }

    public void setSeparator1(String separator1) {
        this.separator1 = separator1 == null ? null : separator1.trim();
    }

    public String getDateVal() {
        return dateVal;
    }

    public void setDateVal(String dateVal) {
        this.dateVal = dateVal == null ? null : dateVal.trim();
    }

    public String getSeparator2() {
        return separator2;
    }

    public void setSeparator2(String separator2) {
        this.separator2 = separator2 == null ? null : separator2.trim();
    }

    public Integer getSeqNo() {
        return seqNo;
    }

    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }

    public String getRemark1() {
        return remark1;
    }

    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    public String getRemark2() {
        return remark2;
    }

    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    public String getRemark3() {
        return remark3;
    }

    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    public String getRemark4() {
        return remark4;
    }

    public void setRemark4(String remark4) {
        this.remark4 = remark4 == null ? null : remark4.trim();
    }

    public String getRemark5() {
        return remark5;
    }

    public void setRemark5(String remark5) {
        this.remark5 = remark5 == null ? null : remark5.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqId=").append(seqId);
        sb.append(", seqDistCd=").append(seqDistCd);
        sb.append(", prefix=").append(prefix);
        sb.append(", separator1=").append(separator1);
        sb.append(", dateVal=").append(dateVal);
        sb.append(", separator2=").append(separator2);
        sb.append(", seqNo=").append(seqNo);
        sb.append(", remark1=").append(remark1);
        sb.append(", remark2=").append(remark2);
        sb.append(", remark3=").append(remark3);
        sb.append(", remark4=").append(remark4);
        sb.append(", remark5=").append(remark5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}