# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER lynn

# 挂载目录
VOLUME /home/lynn
# 创建目录
RUN mkdir -p /home/lynn
# 指定路径
WORKDIR /home/lynn
# 复制jar文件到路径
COPY ./jar/*.jar /home/lynn/
# 启动系统服务
ENTRYPOINT ["java","-jar","lynn-visual-monitor.jar"]