apiVersion: v1
kind: Service
metadata:
  name: ruoyi-nacos
  namespace: kube-ruoyi
  labels:
    app: ruoyi-nacos
spec:
  type: NodePort
  publishNotReadyAddresses: true
  ports:
    - port: 8848
      name: server
      targetPort: 8848
      nodePort: 30848
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
  selector:
    app: ruoyi-nacos